### ISSUE TITLE
Impossible to apply thumbnail in application contexts

### ISSUE THREAD

**Issue by francoperversi** [georchestra/mapstore2-georchestra#101]
It's impossible to apply thumbnail in application contexts. Some categories, like thumbnail category, need to be created in geostore. The following errors are reported in console:

`https://georchestra.geo-solutions.it/mapstore/rest/geostore/resources/resource/40/attributes/thumbnail 404`

`https://georchestra.geo-solutions.it/mapstore/rest/geostore/resources/resource/40/attributes/thumbnail/rest%252Fgeostore%252Fdata%252F101%252Fraw%253Fdecode%253Ddatauri%2526v%253Db68e9e40-0c48-11ea-833e-d14867a0fac6 500`

![thumbnail](https://user-images.githubusercontent.com/54808782/69328609-d1cc5380-0c4f-11ea-9871-d9ee2faca104.gif)

**Comment by offtherailz** [comment]
Watching the requests in newtork during save procedure I see the following:
![image](https://user-images.githubusercontent.com/1279510/69351798-2685c380-0c7c-11ea-8734-eb0a6999f01d.png)
First 404 not found should be normal (trying to get the thumbnail attribute, if exists, to replace the old thumbnail with the new, otherwise create a new one). 
The response of the PUT should be the real problem: 
request does not provide any response, but trying to do a GET request, a more clear message is present, I suspect the reason is the same, but the error in PUT case doesn't return response body:
https://georchestra.geo-solutions.it/mapstore/rest/geostore/resources/resource/16/attributes/thumbnail/rest%252Fgeostore%252Fdata%252F126%252Fraw%253Fdecode%253Ddatauri%2526v%253De1cff9d0-0c72-11ea-aea9-d5ec91ffa923
```
HTTP ERROR 500
Problem accessing /mapstore/rest/geostore/resources/resource/16/attributes/thumbnail/rest%252Fgeostore%252Fdata%252F126%252Fraw%253Fdecode%253Ddatauri%2526v%253De1cff9d0-0c72-11ea-aea9-d5ec91ffa923. Reason:

    Server Error
Caused by:
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL contained a potentially malicious String "%25"
	at org.springframework.security.web.firewall.StrictHttpFirewall.rejectedBlacklistedUrls(StrictHttpFirewall.java:265)
	at org.springframework.security.web.firewall.StrictHttpFirewall.getFirewalledRequest(StrictHttpFirewall.java:245)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:193)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.georchestra.security.UTF8Filter.doFilter(UTF8Filter.java:33)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1602)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
```
So **the problem is related to the GeOrchestra firewall. We should find out a way to disable this check or workaround this problem by changing geostore API

**Comment by tdipisa** [comment]
@Gnafu can you please check this in our dev installation?

**Comment by Gnafu** [comment]
Note, %252F -> %2F -> /
It's a double-encoded slash, so it is either wrongly generated by the client or it comes somehow from the server.
I'll have a look asap

**Comment by offtherailz** [comment]
Yes, double encoding is necessary because of GeoStore API for updating attributes is: 
GET /attribute/<attr-name>/<attr-value>
and we want to store a (relative) URL as <attr-value> : `rest%252Fgeostore%252Fdata%252F126%252Fraw%253Fdecode%253Ddatauri%2526v%253De1cff9d0-0c72-11ea-aea9-d5ec91ffa923` is a URL

**Comment by offtherailz** [comment]
I'm going to solve this adding a PUT entry point compliant (with data in body, not in the URL, avoiding also double encoding) and retrieve data with that method

See https://github.com/geosolutions-it/MapStore2/pull/4673 and https://github.com/geosolutions-it/geostore/pull/198

**Comment by offtherailz** [comment]
@francoperversi noticed that this still not work. It's hard to find out if latest changes has been added to the georchestra mapstore war. @Gnafu let's check together as far as you're avalable.

**Comment by tdipisa** [comment]
@offtherailz a new deploy is needed for that after testing the fix in MS dev and updating the revision here.
