### ISSUE TITLE
failure to read/load georchestra-config

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#106]
added `-Dgeorchestra-config=/etc/georchestra/default.properties` to the JVM environment variables so that mapstore could fetch properties from it, but for some unknown reason the webapp fails to read it:
```
INFO   2019-11-21 14:04:40.061   PropertiesLoaderSupport.loadProperties() - Loading properties file from class path resource [geostore.properties] 
INFO   2019-11-21 14:04:40.061   PropertiesLoaderSupport.loadProperties() - Loading properties file from URL [jar:file:/srv/tomcat/georchestra/webapps/GeOrchestra/WEB-INF/lib/geostore-persistence-1.5.0-SNAPSHO
T.jar!/geostore.properties] 
INFO   2019-11-21 14:04:40.061   PropertiesLoaderSupport.loadProperties() - Loading properties file from ServletContext resource [/etc/georchestra/default.properties] 
...
ERROR   2019-11-21 14:04:40.117   ContextLoader.initWebApplicationContext() - Context initialization failed 
org.springframework.beans.factory.BeanInitializationException: Could not load properties; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/etc/georchestra/default.pro
perties]
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:78)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:663)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:638)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:407)
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4753)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.startup.HostConfig.reload(HostConfig.java:1386)
        at org.apache.catalina.startup.HostConfig.checkResources(HostConfig.java:1350)
        at org.apache.catalina.startup.HostConfig.check(HostConfig.java:1586)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:280)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
        at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1164)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1388)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1392)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1360)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/etc/georchestra/default.properties]
        at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:117)
        at org.springframework.core.io.support.PropertiesLoaderSupport.loadProperties(PropertiesLoaderSupport.java:181)
        at org.springframework.core.io.support.PropertiesLoaderSupport.mergeProperties(PropertiesLoaderSupport.java:161)
        at org.springframework.beans.factory.config.PropertyResourceConfigurer.postProcessBeanFactory(PropertyResourceConfigurer.java:69)
        ... 19 more
```

of course the file exists on the filesystem and is world-readable:
```
-rw-r--r-- 1 root root 3632 Oct 25 14:21 /etc/georchestra/default.properties
```

and the other webapps hosted in the same tomcat server have zero issues reading properties from `default.properties`

**Comment by landryb** [comment]
If i unset `georchestra-config` the error is the following:
```
org.springframework.beans.factory.BeanInitializationException: Could not load properties; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/${georchestra-config}]
```

so the error is simple, missing `file:` qualifier for the file type when pointing at `${georchestra-config}`. Fixing #104 will kill two bird with one stone.

**Comment by landryb** [comment]
And the exact same error for `${geostore-ovr}`:
```
Loading properties file from ServletContext resource [/${geostore-ovr}]
Could not load properties from ServletContext resource [/${geostore-ovr}]: Could not open ServletContext resource [/${geostore-ovr}]
```

**Comment by tdipisa** [comment]
@landryb thank you so much for your feedback, we will check as soon as possible.

**Comment by landryb** [comment]
Looked everywhere in the code but couldnt find a reference to `${geostore-ovr}` without a filetype prefix, so i'm a bit puzzled - maybe it comes from the geostore jar code, and should be just considered as a warning ? (yeah i pushed all logging to DEBUG..)

**Comment by mbarto** [comment]
@landryb a file: prefix is required before the name, as described here: https://github.com/georchestra/mapstore2-georchestra/blob/master/docs/source/database/index.rst

Try to use -Dgeorchestra-config=file:/etc/georchestra/default.properties

**Comment by landryb** [comment]
> @landryb a file: prefix is required before the name, as described here: https://github.com/georchestra/mapstore2-georchestra/blob/master/docs/source/database/index.rst
> 
> Try to use -Dgeorchestra-config=file:/etc/georchestra/default.properties

right, i had missed the `file:/` in the sample line in the doc, sorry. Still, fixing #104 would be nice :) .. and i dunno where the warning for `Could not open ServletContext resource [/${geostore-ovr}]` comes from.

**Comment by mbarto** [comment]
ok, so we will enable the standard georchestra variable.
Going to close this and work on #104
