### ISSUE TITLE
add application/vnd.ogc.se_xml to proxy mimetypeWhitelist

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#110]
this mimetype is used by mapserver to return service errors, and i've seen it being rejected by the mapstore bundled proxy:
```
21-Nov-2019 15:48:31.291 GRAVE [http-nio-8280-exec-70] it.geosolutions.httpproxy.HTTPProxy.executeProxyRequest Error executing HTTP method
 it.geosolutions.httpproxy.HttpErrorException: Content-type application/vnd.ogc.se_xml is not among the ones allowed for this proxy
        at it.geosolutions.httpproxy.MimeTypeChecker.onRemoteResponse(MimeTypeChecker.java:80)
        at it.geosolutions.httpproxy.HTTPProxy.onRemoteResponse(HTTPProxy.java:231)
        at it.geosolutions.httpproxy.HTTPProxy.executeProxyRequest(HTTPProxy.java:694)
        at it.geosolutions.httpproxy.HTTPProxy.doGet(HTTPProxy.java:295)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
```

is there a particular reason for rejecting this mimetype ? It's in the standard, and also used by geoserver afaict.

**Comment by landryb** [comment]
closed by #111
