### ISSUE TITLE
Investigate 404 error on /mapstore

### ISSUE THREAD

**Issue by Gnafu** [georchestra/mapstore2-georchestra#238]
From https://github.com/georchestra/datadir/pull/186
I launched the composition. I have this trace and 404 when going the /mapstore
```
 OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Server version:        Apache Tomcat/7.0.94
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Server built:          Apr 10 2019 16:56:40 UTC
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Server number:         7.0.94.0
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: OS Name:               Linux
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: OS Version:            5.6.12-arch1-1
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Architecture:          amd64
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: JVM Version:           1.8.0_212-8u212-b01-1~deb9u1-b01
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: JVM Vendor:            Oracle Corporation
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: CATALINA_BASE:         /usr/local/tomcat
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: CATALINA_HOME:         /usr/local/tomcat
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Xms512m
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Xmx512m
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -XX:MaxPermSize=128m
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Dgeostore-ovr=file:///etc/georchestra/mapstore/geostore-datasource-ovr.properties
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Dignore.endorsed.dirs=
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Dcatalina.base=/usr/local/tomcat
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Dcatalina.home=/usr/local/tomcat
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.VersionLoggerListener log
 INFO: Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
 May 15, 2020 12:39:01 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
 INFO: Loaded APR based Apache Tomcat Native library 1.2.21 using APR version 1.5.2.
 May 15, 2020 12:39:01 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
 INFO: APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
 May 15, 2020 12:39:01 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
 INFO: OpenSSL successfully initialized (OpenSSL 1.1.0j  20 Nov 2018)
 May 15, 2020 12:39:01 PM org.apache.coyote.AbstractProtocol init
 INFO: Initializing ProtocolHandler ["http-apr-8080"]
 May 15, 2020 12:39:01 PM org.apache.coyote.AbstractProtocol init
 INFO: Initializing ProtocolHandler ["ajp-apr-8009"]
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.Catalina load
 INFO: Initialization processed in 402 ms
 May 15, 2020 12:39:01 PM org.apache.catalina.core.StandardService startInternal
 INFO: Starting service Catalina
 May 15, 2020 12:39:01 PM org.apache.catalina.core.StandardEngine startInternal
 INFO: Starting Servlet Engine: Apache Tomcat/7.0.94
 May 15, 2020 12:39:01 PM org.apache.catalina.startup.HostConfig deployWAR
 INFO: Deploying web application archive /usr/local/tomcat/webapps/mapstore.war
 May 15, 2020 12:39:02 PM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
 INFO: validateJarFile(/usr/local/tomcat/webapps/mapstore/WEB-INF/lib/servlet-api-2.5-6.1.14.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
 May 15, 2020 12:39:02 PM org.apache.catalina.loader.WebappClassLoaderBase validateJarFile
 INFO: validateJarFile(/usr/local/tomcat/webapps/mapstore/WEB-INF/lib/servlet-api-2.5.jar) - jar not loaded. See Servlet Spec 3.0, section 10.7.2. Offending class: javax/servlet/Servlet.class
 May 15, 2020 12:39:05 PM org.apache.catalina.startup.TldConfig execute
 INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
 log4j:ERROR Could not read configuration file from URL [file:/usr/local/tomcat/../webapps/mapstore/WEB-INF/classes/log4j.properties].
 java.io.FileNotFoundException: /usr/local/tomcat/../webapps/mapstore/WEB-INF/classes/log4j.properties (No such file or directory)
   at java.io.FileInputStream.open0(Native Method)
   at java.io.FileInputStream.open(FileInputStream.java:195)
   at java.io.FileInputStream.<init>(FileInputStream.java:138)
   at java.io.FileInputStream.<init>(FileInputStream.java:93)
   at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
   at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
   at java.net.URL.openStream(URL.java:1045)
   at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:433)
   at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:336)
   at org.springframework.util.Log4jConfigurer.initLogging(Log4jConfigurer.java:72)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
   at org.springframework.beans.factory.config.MethodInvokingFactoryBean.doInvoke(MethodInvokingFactoryBean.java:162)
   at org.springframework.beans.factory.config.MethodInvokingFactoryBean.afterPropertiesSet(MethodInvokingFactoryBean.java:152)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1477)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1417)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
   at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:456)
   at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:291)
   at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
   at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:288)
   at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:190)
   at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:563)
   at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)
   at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)
   at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
   at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
   at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
   at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5197)
   at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5720)
   at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
   at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:1018)
   at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:994)
   at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
   at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1127)
   at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:2020)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   at java.lang.Thread.run(Thread.java:748)
 log4j:ERROR Ignoring configuration file [file:/usr/local/tomcat/../webapps/mapstore/WEB-INF/classes/log4j.properties].
 May 15, 2020 12:39:09 PM org.apache.catalina.core.StandardContext startInternal
 SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
 May 15, 2020 12:39:09 PM org.apache.catalina.core.StandardContext startInternal
 SEVERE: Context [/mapstore] startup failed due to previous errors
 May 15, 2020 12:39:09 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
 SEVERE: The web application [/mapstore] registered the JDBC driver [org.postgresql.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
 May 15, 2020 12:39:10 PM org.apache.catalina.startup.HostConfig deployWAR
 INFO: Deployment of web application archive /usr/local/tomcat/webapps/mapstore.war has finished in 8,300 ms
 May 15, 2020 12:39:10 PM org.apache.coyote.AbstractProtocol start
 INFO: Starting ProtocolHandler ["http-apr-8080"]
 May 15, 2020 12:39:10 PM org.apache.coyote.AbstractProtocol start
 INFO: Starting ProtocolHandler ["ajp-apr-8009"]
 May 15, 2020 12:39:10 PM org.apache.catalina.startup.Catalina start
 INFO: Server startup in 8362 ms
```

**Comment by Gnafu** [comment]
Asked for steps to reproduce.
Will try with a new build and setup of the whole geOrchestra stack

**Comment by Gnafu** [comment]
Fixed by https://github.com/georchestra/docker/pull/58/commits/ee9fa7941e8d6e2ced064f479dcc696fea4732b5
