### ISSUE TITLE
mention build dependencies in README.md ? [npm build failure]

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#3]
Dunno what's the minimal nodejs/npm version needed, but on debian stretch (yeah i know oldstable) i installed them from `stretch-backports` so got `npm (5.8.0+ds6-2~bpo9+1)` and `nodejs (8.11.1~dfsg-2~bpo9+1)` and after it installed the complete earth in `~/.npm` i had it failing to build:
```
[16/09 15:42] landry@build.thruxton:/data/src/georchestra/mapstore2-georchestra $bash ./build.sh
... some npm warnings, of course..
> GeOrchestra@1.0.0 postinstall /data/src/georchestra/mapstore2-georchestra
> node checkCesium.js
> GeOrchestra@1.0.0 compile /data/src/georchestra/mapstore2-georchestra
> npm run clean && mkdirp ./dist && webpack --config prod-webpack.config.js --env.production
> GeOrchestra@1.0.0 clean /data/src/georchestra/mapstore2-georchestra
> rimraf dist
....
Hash: 511b45ed6120fd9825bc
Version: webpack 2.2.1
Time: 171723ms
  [22] ./~/style-loader/addStyles.js 6.09 kB {10} {11} {12} [built]
 [825] ./MapStore2/web/client/actions/version.js 1.61 kB {10} {11} {12} [built]
[5211] ./MapStore2/web/client/themes/console/theme.less 41 bytes {19} [built]
[5212] ./MapStore2/web/client/themes/dark/theme.less 41 bytes {18} [built]
[5213] ./MapStore2/web/client/themes/default/theme.less 41 bytes {17} [built]
[5214] ./MapStore2/web/client/themes/geosolutions/theme.less 41 bytes {16} [built]
[5215] ./MapStore2/web/client/themes/wasabi/theme.less 41 bytes {15} [built]
[5216] ./MapStore2/web/client/product/api.jsx 2.12 kB {11} [built]
[5217] ./MapStore2/web/client/product/embedded.jsx 2.06 kB {12} [built]
[5218] ./js/app.jsx 2.8 kB {10} [built]
[5219] (webpack)-dev-server/client?http://0.0.0.0:8081 5.28 kB {13} [built]
[5220] (webpack)/hot/only-dev-server.js 2.29 kB {14} [built]
[5441] ./~/css-loader!./~/postcss-loader!./~/less-loader!./MapStore2/web/client/themes/console/theme.less 442 kB [built]
[5443] ./~/css-loader!./~/postcss-loader!./~/less-loader!./MapStore2/web/client/themes/default/theme.less 441 kB [built]
[5444] ./~/css-loader!./~/postcss-loader!./~/less-loader!./MapStore2/web/client/themes/geosolutions/theme.less 442 kB [built]
    + 5569 hidden modules

ERROR in minifying GeOrchestra-api.js
Unexpected token: operator (>)

ERROR in minifying GeOrchestra-embedded.js
Unexpected token: operator (>)

ERROR in minifying GeOrchestra.js
Unexpected token: operator (>)
Child html-webpack-plugin for "index.html":
       [0] ./~/html-webpack-plugin/lib/loader.js!./indexTemplate.html 4.11 kB {0} [built]
...
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! GeOrchestra@1.0.0 compile: `npm run clean && mkdirp ./dist && webpack --config prod-webpack.config.js --env.production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the GeOrchestra@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 5.8.0 → 6.11.3    │
   │       Run npm i npm to update        │
   │                                      │
   ╰──────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/landry/.npm/_logs/2019-09-16T13_47_41_270Z-debug.log
```

the content of the debug log is below:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'compile' ]
2 info using npm@5.8.0
3 info using node@v8.11.1
4 verbose run-script [ 'precompile', 'compile', 'postcompile' ]
5 info lifecycle GeOrchestra@1.0.0~precompile: GeOrchestra@1.0.0
6 info lifecycle GeOrchestra@1.0.0~compile: GeOrchestra@1.0.0
7 verbose lifecycle GeOrchestra@1.0.0~compile: unsafe-perm in lifecycle true
8 verbose lifecycle GeOrchestra@1.0.0~compile: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/data/src/georchestra/mapstore2-georchestra/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin/:/usr/sbin/
9 verbose lifecycle GeOrchestra@1.0.0~compile: CWD: /data/src/georchestra/mapstore2-georchestra
10 silly lifecycle GeOrchestra@1.0.0~compile: Args: [ '-c',
10 silly lifecycle   'npm run clean && mkdirp ./dist && webpack --config prod-webpack.config.js --env.production' ]
11 silly lifecycle GeOrchestra@1.0.0~compile: Returned: code: 2  signal: null
12 info lifecycle GeOrchestra@1.0.0~compile: Failed to exec compile script
13 verbose stack Error: GeOrchestra@1.0.0 compile: `npm run clean && mkdirp ./dist && webpack --config prod-webpack.config.js --env.production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid GeOrchestra@1.0.0
15 verbose cwd /data/src/georchestra/mapstore2-georchestra
16 verbose Linux 4.9.0-9-amd64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "compile"
18 verbose node v8.11.1
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 2
22 error GeOrchestra@1.0.0 compile: `npm run clean && mkdirp ./dist && webpack --config prod-webpack.config.js --env.production`
22 error Exit status 2
23 error Failed at the GeOrchestra@1.0.0 compile script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

if there are specific versions of npm/nodejs newer than this, it should be specified ..

On an unrelated note, it seems the console in georchestra uses a bundled version of npm to build, since i had no need for npm/nodejs installed systemwide to build the console...

**Comment by mbarto** [comment]
@landryb the build issues should be fixed by https://github.com/georchestra/mapstore2-georchestra/commit/bffc1c2c8a861640f6b081c677f3e4fb3d47017f
can you please test again and confirm?
I am going to add notes in the readme about build dependencies / instructions

**Comment by landryb** [comment]
sadly master stills fails to build here with the exact same errors (`Unexpected token: operator (>)`), with the same npm/nodejs versions (5.8.0/8.11.1)

**Comment by landryb** [comment]
Bah, disregard my last comment. mapstore2 submodule was pointing at `0908662c7327b0813800cc0ec9aac64483390d3f MapStore2 (2017.03.00-1119-g0908662c)`, `master` builds fine after a `git submodule update` - it just blows at the end because it looks for a chrome binary (wtf?)

Needless to say that i'm not going to install chrome on my headless builders, so i guess i'll have to find a way to disable tests :)
