### ISSUE TITLE
failure to print WMTS background layers coming from non-geoserver services 

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#399]
on https://ids.craig.fr/mapstore/ i have a list of WMTS backgrounds configured via new.json
```
      "layers" : [
         {
            "title" : "Openstreetmap",
            "name" : "mapnik",
            "source" : "osm",
            "group" : "background",
            "type" : "osm",
            "visibility" : false
         },
         {
            "id": "dde414d0-3dfb-11eb-954f-85311a469d4b",
            "title": "Plan IGN v2",
            "type": "wmts",
            "visibility" : true,
            "group": "background",
            "url": "https://wxs.ign.fr/1wexxrf38g4k60sfffkgyotp/geoportail/wmts",
            "name": "GEOGRAPHICALGRIDSYSTEMS.PLANIGNV2",
            "format": "image/png",
            "style": "normal",
            "allowedSRS": { "EPSG:3857": true },
            "matrixIds": [ "PM", "EPSG:3857" ],
            "tileMatrixSet": true,
            "bbox": {
                "crs": "EPSG:4326",
                "bounds": {
                    "minx": "-175",
                    "miny": "-85",
                    "maxx": "175",
                    "maxy": "85"
                }
            }
         },
         {
            "id": "f4c9e5d0-3dfb-11eb-954f-85311a469d4b",
            "title": "Photographie aérienne",
            "type": "wmts",
            "group": "background",
            "thumbURL": "https://ids.craig.fr/mapstore/dist/MapStore2/web/client/plugins/background/assets/img/Aerial.j
pg",
            "url": "https://wxs.ign.fr/1wexxrf38g4k60sfffkgyotp/geoportail/wmts",
            "name": "ORTHOIMAGERY.ORTHOPHOTOS",
            "format": "image/jpeg",
            "style": "normal",
            "visibility" : false,
            "allowedSRS": { "EPSG:3857": true },
            "matrixIds": [ "PM", "EPSG:3857" ],
            "tileMatrixSet": true,
            "bbox": {
                "crs": "EPSG:4326",
                "bounds": {
                    "minx": "-63.160706980",
                    "miny": "-21.401263115",
                    "maxx": "55.846431162",
                    "maxy": "51.112419947"
                }
            }
         },
         {
            "title" : "Pas de fond",
            "fixed" : true,
            "source" : "ol",
            "group" : "background",
            "type" : "empty"
         }
      ],
```
(the IGN source is configured a bit below in `backgrounds`)

trying to print a pdf with a WMTS background blows with
```
Error while generating PDF:
org.mapfish.print.JsonMissingException: attribute [spec.layers[0].requestEncoding] missing
	at org.mapfish.print.utils.PJsonObject.getString(PJsonObject.java:56)
	at org.mapfish.print.map.readers.WMTSMapReader.<init>(WMTSMapReader.java:75)
	at org.mapfish.print.map.readers.WMTSMapReader.<init>(WMTSMapReader.java:40)
	at org.mapfish.print.map.readers.WMTSMapReader$Factory.create(WMTSMapReader.java:45)
	at org.mapfish.print.map.readers.MapReaderFactoryFinder.create(MapReaderFactoryFinder.java:39)
	at org.mapfish.print.map.MapChunkDrawer.renderMap(MapChunkDrawer.java:142)
	at org.mapfish.print.map.MapChunkDrawer.renderImpl(MapChunkDrawer.java:87)
	at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
...
```
i guess this has something to do with the wmts layer configuration but i'm not sure what ..

no issues when printing wms overlay coming from geoserver, but a wmts overlay layer coming from mapproxy (https://wmts.craig.fr/ortho/service) also fails, with a slightly different error message::
```
Error on printing: Error while generating PDF: 
org.mapfish.print.JsonMissingException: attribute [spec.layers[0].style] missing
    at org.mapfish.print.utils.PJsonObject.getString(PJsonObject.java:56)
    at org.mapfish.print.map.readers.WMTSMapReader.<init>(WMTSMapReader.java:78)
    at org.mapfish.print.map.readers.WMTSMapReader.<init>(WMTSMapReader.java:40) 
 
```

this is with mapstore2-georchestra from https://github.com/georchestra/mapstore2-georchestra/commit/b79d76808274663cf475e0b82ed4ce66d3240287

**Comment by landryb** [comment]
@catmorales @tdipisa @offtherailz  fwiw i can reproduce the issue on https://georchestra.geo-solutions.it/mapstore/, adding a WMTS background layer from our public mapproxy instance at https://tiles.craig.fr/ortho/service and trying to print the view exhibits the issue.

**Comment by landryb** [comment]
@offtherailz any chance you'd be able to look into this ? Since we've migrated our users to use ms2-cadastrapp by default, and we have external non-geoserver WMTS backgrounds, they complain that printing is broken.

**Comment by landryb** [comment]
Fwiw, with the browser console, if i live-edit the json sent by mapstore to mapfishprint backend to add `requestEncoding: "KVP"` for the WMTS layer coming from ign geoservices or our mapproxy, then mapfishprint succeeds at printing the pdf with the WMTS layer.

Now i know it's a small bug in mapstore somewhere... interoperability is hard.

what is infuriating is that with a geowebcache-backed WMTS layer (say, a layer from https://osm.geobretagne.fr/gwc01/service/wmts), mapstore *does* add the `requestEncoding` parameter and the print succeeds right away.

**Comment by landryb** [comment]
my understanding of the mapstore code is that in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/WMTSUtils.js#L56 the code looks for the `GetTile` operation in the getcapabilities (which *is* in a WMTS getcapabilities coming from gwc, ex https://osm.geobretagne.fr/gwc01/service/wmts?request=GetCapabilities&version=1.0.0, but also in http://tiles.craig.fr/ortho/service?service=wmts&request=getcapabilities ....), if not defined it looks for `restful` then sortof defaults to restful ?
the `WMTSUtils.getOperation(operations, "GetTile", "RESTful") && "RESTful"` bit is arcane to me.

printing a wmts layer from https://wxs.ign.fr/essentiels/geoportail/wmts?SERVICE=WMTS&REQUEST=GetCapabilities seems to work when the layer is added afterwards, but not when the layer comes from a background layer configured directly in `new.json`. Maybe i'll retry, force-adding `"requestEncoding": "KVP"` in the catalog definition in `new.json`, but from my understanding it should be the default..

trying to print a wmts layer added after loading the map from http://tiles.craig.fr/ortho/service?service=wmts&request=getcapabilities fails with `Error on printing: Error while generating PDF: org.mapfish.print.JsonMissingException: attribute [spec.layers[0].style] missing` so there are imo two separate options:

- failure to print WMTS layers preloaded as backgrounds ?
- failure to print WMTS layers loaded in a 2nd time

**Comment by landryb** [comment]
sadly, same failure (`attribute [spec.layers[0].requestEncoding] missing `) with `requestEncoding` added to the background layer definition in `new.json`. Bad hope...

**Comment by landryb** [comment]
hmm ... maybe https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/PrintUtils.js#L564 is the spot where things go wrong if `layer.RequestEncoding` has no value ? same thing, that could also explain the `attribute [spec.layers[0].style] missing` errors where the layer has no found style for some reason ?

**Comment by landryb** [comment]
@offtherailz fwiw i'm trying a build with this diff in the Mapstore submodule:
```
--- a/web/client/utils/PrintUtils.js
+++ b/web/client/utils/PrintUtils.js
@@ -460,9 +460,9 @@ export const specCreators = {
                 ...dimensionParams,
                 "matrixIds": matrixIds,
                 "matrixSet": tileMatrixSetName,
-                "style": layer.style,
+                "style": layer.style || 'default',
                 "name": layer.name,
-                "requestEncoding": layer.requestEncoding === "RESTful" ? "REST" : layer.requestEncoding,
+                "requestEncoding": layer.requestEncoding === "RESTful" ? "REST" : layer.requestEncoding || 'KVP',
                 "opacity": getOpacity(layer),
                 "version": layer.version || "1.0.0"
             };
```
but i'd be curious to know why in some circumstances `requestEncoding` and/or `style` can be empty/undef...

**Comment by landryb** [comment]
as for the default style value, it seems what mapproxy sends has
```
<Style>
<ows:Identifier>default</ows:Identifier>
</Style>
```
while gwc sends
```
<Style isDefault="true">
<ows:Identifier/>
</Style>
```
and ign geoservices send
```
<Style isDefault="true">
<ows:Title>PCI vecteur</ows:Title>
<ows:Abstract>Légende de la couche PCI vecteur</ows:Abstract>
....

```
and it seems the code in https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/WMTSUtils.js#L106 only supports the latter style (eg enforces the presence of `isDefault="true"`).

Could the code be improved to default to the first style, if only one style is listed in `GetCapabilities` ?

**Comment by landryb** [comment]
the last time this was changed was for geosolutions-it/MapStore2#6551 so the method *can* return null, so that would break printing anyway. Maybe there should be a failsafe default ?

**Comment by landryb** [comment]
the above diff allows me to print WMTS layers added from https://tiles.craig.fr/ortho/service?service=wmts&request=getcapabilities, and also to print background WMTS layers coming from IGN geoportail WMTS services.

I agree it might not be the *right* fix but at least this goes in the right direction.

**Comment by landryb** [comment]
i've looked at the OGC WMTS spec from https://www.ogc.org/standards/wmts and on page 35 the `isDefault` attribute is *optional* so it seems the `GetCapabilities` sent by mapproxy is valid..
