### ISSUE TITLE
Layer styles cannot be edited

### ISSUE THREAD

**Issue by severinmenard** [georchestra/mapstore2-georchestra#435]
Seems to be a bug for our MapStore (last update on October 14) for geOrchestra: no layer style can be edited, as shown on this example:

![Screenshot510](https://user-images.githubusercontent.com/1291055/144769873-f1d3c141-35e7-43ea-9605-547860d805ba.png)

This affects either the layer from our geOrchestra instance or any external layer, as shown on [this map ](https://ifl.francophonelibre.org/mapstore/#/viewer/openlayers/267) where "Arbres d'alignements" comes from an external geOrchestra, that does not have any issue with style editing. In our instance, it looks that the previous screenshot: 

![Screenshot511](https://user-images.githubusercontent.com/1291055/144770243-8cb70130-e3ad-4a82-92c6-9ddf33a17cf2.png)

This of course a huge limitation for the user experience. Gaetanbrl and pierrejego from JDev tried to solve it but did not find the solution so far. Any idea?

**Comment by Gaetanbrl** [comment]
In addition, we can read [this doc section](https://mapstore.readthedocs.io/en/latest/user-guide/layer-settings/) about styler but how works the style between mapstore2-georchestra and geoserver ?

What is the correct config to use the styler ? (data security, roles, group, workspace security, use custom style instread of default GeoServer style, others...).

Sometimes we can't style a layer, sometimes we could... i don't really understant the config / rules behind the woods.

**Comment by severinmenard** [comment]
EDIT: the StyleEditor plugin is dully activated in the map context, as shown on [this video](https://llg-collabora.ethibox.fr/s/efrD48pRFrzDqDM)

**Comment by Gaetanbrl** [comment]
After plugin config + clean data (workspace, broken layers....) + clean security rules (on workspace, layers etc.) the style editor plugin seems works fin for admin user and a correct plugin config (thanks @landryb) :

https://mapstore.geosolutionsgroup.com/mapstore/docs/api/plugins#plugins.StyleEditor

About CSS, jar files was upgraded as already explained but CSS is still broken until now :

 GeoServer 2.17.4-georchestra return log :
```
2022-02-07 14:43:40,303 ERROR [geoserver.rest] - Error creating extended parser class: null
java.lang.RuntimeException: Error creating extended parser class: null
	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
	at org.geotools.styling.css.CssParser.getInstance(CssParser.java:108)
	at org.geotools.styling.css.CssParser.parse(CssParser.java:119)
	at org.geoserver.community.css.web.CssHandler.convertToSLD(CssHandler.java:149)
	at org.geoserver.community.css.web.CssHandler.parse(CssHandler.java:139)
	at org.geoserver.rest.catalog.StyleController.styleSLDPost(StyleController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by Gaetanbrl** [comment]
CSS works fine after upgrade geoserver libs to :

- accessors-smart-1.2.jar
- json-path-2.4.0.jar
- json-smart-2.3.jar

Tested & approved with : 

- 2.17.4-georchestra
- 2.18.3-georchestra

**Comment by Gaetanbrl** [comment]
After change localConfig.json and adapt correct styleEditor config, all seems works better.
The baseUrl target a wrong geoserver URL.

```
            {
              "name": "StyleEditor",
              "cfg": {
                "editingAllowedRoles": null,
                "enableSetDefaultStyle": true,
                "styleService": {
                  "baseUrl":"/llg/",
                  "formats": ["sld", "css"],
                  "availableUrls": ["llg","/atelier/","/formation/"]
                }
              }
            },
```
@severinmenard => closable issue ?

**Comment by landryb** [comment]
well, from that config snippet, what is exactly the change or combination of changes that allows to modify the default style of a layer which only has a single style ?  `"enableSetDefaultStyle": true,` ? what was the previously non-working config ?

**Comment by Gaetanbrl** [comment]
my bad, this fix allow @severinmenard to create / edit a new style created from mapstore (not create in geoserver first).

The previous config contain a wrong baseUrl : 

Change `"baseUrl":"/atelier/",` by `"baseUrl":"/llg/",` because they works with `/llg` ...

**Comment by landryb** [comment]
so that doesnt fix https://github.com/georchestra/mapstore2-georchestra/issues/435#issuecomment-1074121664 right ?

**Comment by Gaetanbrl** [comment]
Next, if you create a new layer style from mapstore styleEditor and come back later, you can't edit the previous style...

**Comment by Gaetanbrl** [comment]
About code button and disabled state : 

https://github.com/geosolutions-it/MapStore2/blob/6c8af917025f41a6bd27c48b9209ffb5b666e7ef/web/client/components/styleeditor/StyleToolbar.jsx#L108-L113

**Comment by Gaetanbrl** [comment]
And here, maybe more logic to understand something about this button...

https://github.com/geosolutions-it/MapStore2/blob/6c8af917025f41a6bd27c48b9209ffb5b666e7ef/web/client/components/styleeditor/__tests__/StyleToolbar-test.jsx#L75-L82
