### ISSUE TITLE
embedding geostory or dashboard triggers a 500 error code

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-georchestra#483]
trying to share a dashboard or a geostory via iframe blows:

- https://georchestra.geo-solutions.it/mapstore/geostory-embedded.html
- https://georchestra.geo-solutions.it/mapstore/dashboard-embedded.html 
- 
both trigger a 500 error code with:
```
net.sf.ehcache.constructs.web.ResponseHeadersNotModifiableException: Failure when attempting to set Content-Encoding: gzip
	net.sf.ehcache.constructs.web.ResponseUtil.addGzipHeader(ResponseUtil.java:126)
	net.sf.ehcache.constructs.web.filter.GzipFilter.doFilter(GzipFilter.java:89)
	net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:89)
```

seems to be specific to ms2-georchestra as https://mapstore.geosolutionsgroup.com/mapstore/dashboard-embedded.html#/7586 renders fine.

**Comment by landryb** [comment]
full traceback in mapstore log:
```
WARN   2022-02-03 11:40:42.745   Filter.logThrowable() - Throwable thrown during doFilter on request with URI: /mapstore/dashboard-embedded.html and Query: nullFailure when attempting to set Content-Encoding: gzip 
net.sf.ehcache.constructs.web.ResponseHeadersNotModifiableException: Failure when attempting to set Content-Encoding: gzip
        at net.sf.ehcache.constructs.web.ResponseUtil.addGzipHeader(ResponseUtil.java:126)
        at net.sf.ehcache.constructs.web.filter.GzipFilter.doFilter(GzipFilter.java:89)
        at net.sf.ehcache.constructs.web.filter.Filter.doFilter(Filter.java:89)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by landryb** [comment]
embedding a map via `mapstore/embedded.html` doesnt trigger this issue so this seems specific to geostories/dashboards.

**Comment by landryb** [comment]
i can confirm that #488 fixes the issue in master, thanks !
